### ISSUE TITLE
New package leafdown

### ISSUE THREAD

**Issue by andreash0** [nanxstats/awesome-shiny-extensions#14]
Hey @nanxstats,

we have developed a package [`leafdown`](https://github.com/hoga-it/leafdown) that provides drilldown functionality for leaflet choropleths in shiny apps.
Would you consider adding it to the list?

**Comment by nanxstats** [comment]
@andreash0 Looking great, please send a pull request. Thanks!

**Comment by nanxstats** [comment]
Thanks! Merged.
