### ISSUE TITLE
shinyTree

### ISSUE THREAD

**Issue by trafficonese** [nanxstats/awesome-shiny-extensions#2]
The shinyTree link is not the "official" repo and instead links to a fork, which is not up to date.

You might want to change it with this link:
https://github.com/shinyTree/shinyTree

**Comment by nanxstats** [comment]
@trafficonese -thanks! Fixed in https://github.com/nanxstats/awesome-shiny-extensions/commit/4b04798ede3276553cd425ad7272209ce61e62cd.
