### ISSUE TITLE
shiny.fluent

### ISSUE THREAD

**Issue by kylebutts** [nanxstats/awesome-shiny-extensions#23]
Hi there, great set of resources! Another cool set of packages are shiny.fluent and shiny.react which uses Microsoft's Fluent design system:

https://github.com/Appsilon/shiny.fluent

**Comment by nanxstats** [comment]
@kylebutts Very cool! Would you mind sending a pull request to add these two packages under [Generic Theming](https://github.com/nanxstats/awesome-shiny-extensions#generic-theming) and [React](https://github.com/nanxstats/awesome-shiny-extensions#react), respectively?

**Comment by nanxstats** [comment]
Fixed by https://github.com/nanxstats/awesome-shiny-extensions/commit/3a2b4bb2b75dace6b0e55b29049e608100b10f5b. Thanks again for the hint!
