### ISSUE TITLE
The link to arcDiagramR is dead

### ISSUE THREAD

**Issue by psyguy** [nanxstats/awesome-shiny-extensions#24]
Hi,

Basically the title: The link to the package [arcDiagramR](https://github.com/hepplerj/arcDiagramR) of @hepplerj does not work anymore.

**Comment by nanxstats** [comment]
Thanks for the hint - I didn't find any proper successors of the repo - so removed in https://github.com/nanxstats/awesome-shiny-extensions/commit/b9a9652103d2d2291dc50ea49953a369a9781c9e.
