### ISSUE TITLE
Consider adding shinyEffects

### ISSUE THREAD

**Issue by ismirsehregal** [nanxstats/awesome-shiny-extensions#26]
https://github.com/RinteRface/shinyEffects

**Comment by nanxstats** [comment]
Nice -@ismirsehregal do you mind creating a pull request for this? I suggest putting it under section [Animation Effects](https://github.com/nanxstats/awesome-shiny-extensions#animation-effects).

**Comment by ismirsehregal** [comment]
Sure:

https://github.com/nanxstats/awesome-shiny-extensions/pull/27

**Comment by nanxstats** [comment]
Merged, thanks!
