### ISSUE TITLE
Rstudio layout

### ISSUE THREAD

**Issue by ricoderks** [nanxstats/awesome-shiny-extensions#31]
Hi Nan,

Thank you for sharing this awesome list! I have a question and hope you can help me. I have an idea to develop an app with layout which Rstudio uses. I mean, the screen is divided in 4 area's and are resizable. I like the resizing with just a simple bar a lot. This is what I would like to use to show multiple plots on the screen. Have you ever seen a shiny extension who can split the screen in 4 areas and do this? 

Cheers, Rico

**Comment by nanxstats** [comment]
The closest thing I can think of is [shinypanels](https://github.com/datasketch/shinypanels) with collapsible horizontal panels and [shinyjqui](https://github.com/Yang-Tang/shinyjqui) offering resizable elements.

**Comment by ricoderks** [comment]
Hi Nan,

Thanks, I'll have a look at both.

Cheers, Rico

**Comment by DagHjermann** [comment]
You may have to add javascript to the app. A possibility is to use the Javascript library [split](https://github.com/nathancahill/split), as can be seen from [this example](https://jsfiddle.net/mdineshkumarcs/h3cvm2ws/) that I found linked from [this SO answer](https://stackoverflow.com/a/40358132).    

I have never tried to add custom javascript myslef, but this seems to be a friendly guide to it:
[Why and how to use JS in your Shiny app (brodrigues.co)](https://www.brodrigues.co/blog/2022-10-01-why_js_shiny/)

**Comment by ricoderks** [comment]
Hi Dag,

Thanks for your tips!!

Cheers, Rico

**Comment by ismirsehregal** [comment]
How about: https://github.com/rstudio/gridlayout

The library was announced during [rstudio::conf(2022)](https://www.rstudio.com/blog/four-announcements-from-rstudio-conf-2022/#new-developments-in-shiny-shiny-for-python-shiny-without-a-server-a-visual-shiny-ui-editor-and-more).

Also please see the [application layout guide](https://shiny.rstudio.com/articles/layout-guide.html).

**Comment by ricoderks** [comment]
Hi ismirsehregal,

Thanks for your tips!!

Cheers, Rico
