### ISSUE TITLE
Automated URL checker

### ISSUE THREAD

**Issue by nanxstats** [nanxstats/awesome-shiny-extensions#32]
We should create a link checker script (preferably in R) to ensure all the links are useable.

This doesn't have to run as GitHub Actions but should be generally useful as a manual script to ran as a start.

One special challenge: to check GitHub links reliably, we need to specify the GitHub token in the requests, as there is an obvious rate limit there.

**Comment by mcanouil** [comment]
With #38 (and typo fix from #39) this issue should be fixed.

**Comment by nanxstats** [comment]
Very nice, let's close this for now. 👍
